CREATE VIEW DAY_BY_DAY(
  D_DATE,
  SUM_KASSA,
  SUM_SALE)
AS
SELECT
  	K_DATE,
    SUMM,
    0
  FROM
  	KASSA
  WHERE
    ((SELECT C_TYPE FROM CUSTOMERS WHERE CUSTOMERS.ID = KASSA.CLIENT_ID) <> 0) and 
    ((SELECT C_TYPE FROM CUSTOMERS WHERE CUSTOMERS.ID = KASSA.CLIENT_ID) <> 4) and   
    ((SELECT C_TYPE FROM CUSTOMERS WHERE CUSTOMERS.ID = KASSA.CLIENT_ID) <> 5) and        
    (IN_USE = 1)
UNION
  SELECT
  	S_DATE,
    0,
    SUM_TOTAL
  FROM
  	SALE_N
UNION
  SELECT
  	R_DATE,
    0,
    SUMM_TOTAL * -1
  FROM
  	RETURN_CUST_N;